### ISSUE TITLE
[PE-D] Misleading command summary

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W12-2/tp#100]
![image.png](https://raw.githubusercontent.com/aikenwx/ped/main/files/3d1949b8-a988-4418-8fe9-441176dca94c.png)

I was led to believe that `listTasks` has the ability to list tasks by date from this command summary, even though it was not implemented in the JAR build

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: aikenwx/ped#6

**Comment by ambroseboo** [comment]
Duplicate issue
