### ISSUE TITLE
[PE-D] Missing details in UG for `Editing the data file`

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W12-2/tp#116]
`[JAR file location]/data/taskrecords.json` should also be included here

![image.png](https://raw.githubusercontent.com/aikenwx/ped/main/files/970595ae-0cfe-4fe4-858d-6c533f99767f.png)

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: aikenwx/ped#10

**Comment by zhenxuantan** [comment]
Someone did this already.
